language: python
sudo: false
python:
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
    allow_failures:
        - python: 3.7-dev

# command to install dependencies
install:
  - python setup.py build sdist
  - pip install -r development.txt

# command to run tests
script: pytest
